version: 2
mergeable:
  - when: pull_request.*, pull_request_review.*
    validate:
      - do: head_ref
        regex: '^(feature|bugfix|hotfix|build)\/[A-Z]+-[0-9]+-[A-Z]{2,5}$'
        message: 'Branch name must follow <keyword>/<JIRA_ID>-<signature>. Example: feature/JIRA-1234-IL'

      - do: commit
        message:
          regex: '(?=.*(^((build:|chore:|ci:|docs:|feat:|fix:|perf:|refactor:|revert:|update:|create:|style:|test:)(( )|())([a-z]\w{1,72})))|(Merge(.*\s*)*)|(Initial commit$))(?=.*([A-z]+(-)[0-9]))'
          message: 'Invalid commit message format. Use: <type>: <subject> <JIRA-ID>'

      - do: title
        must_include:
          regex: '(^[A-z]+(-| )[0-9]+(:|-| )(\w|\W)+$)'

    pass:
      - do: checks
        status: success
        payload:
          title: 'Run has been Completed!'
          summary: "All validators passed. {{validationCount}} checks ran."

    fail:
      - do: checks
        status: failure
        payload:
          title: 'Run Failed'
          summary: "Status: {{toUpperCase validationStatus}}. {{failCount}} validations failed."
